// data.js — Data akun siswa & admin (hardcoded).
// accounts di-generate dari data siswa (Kelas X, Kelas XI, dan Kelas XII).
// Total: 646 siswa, password sama untuk semua: VOTING

export const accounts = [
  // Kelas XI A (dahulu Kelas XA)
  { nama: "Ahmad Subarashi Firjatullah", password: "VOTING" },
  { nama: "Aira Khedira Anastasha", password: "VOTING" },
  { nama: "Aldo Pratama Putra", password: "VOTING" },
  { nama: "Ananda Khairil Al - Fijar", password: "VOTING" },
  { nama: "Arina Sitha Nazasalfa", password: "VOTING" },
  { nama: "Az Zahra Putri Zilvylia", password: "VOTING" },
  { nama: "Azzahwa Naisya Dwi Putri", password: "VOTING" },
  { nama: "Chyka Salsabila", password: "VOTING" },
  { nama: "Daffa Hafizd Supriyadi", password: "VOTING" },
  { nama: "Dafina Sazwiyan", password: "VOTING" },
  { nama: "Dennis Dwi Putra", password: "VOTING" },
  { nama: "Erdina Syifa Kamarina", password: "VOTING" },
  { nama: "Fayedha Tunizaula Dhaiyfiyara", password: "VOTING" },
  { nama: "Fazril Wildanhakim", password: "VOTING" },
  { nama: "Humaira Nurul Azka", password: "VOTING" },
  { nama: "Inayah Safitri", password: "VOTING" },
  { nama: "Karina Nuril Awaliyah", password: "VOTING" },
  { nama: "Khairunnisa", password: "VOTING" },
  { nama: "M. Fadhil Ilham Suprapto", password: "VOTING" },
  { nama: "Muhammad Adilla Azhar", password: "VOTING" },
  { nama: "Muhammad Ikhlas Raditya", password: "VOTING" },
  { nama: "Muhammad Rava Al Ziqry", password: "VOTING" },
  { nama: "Muhammad Refiro Irkuwiputra", password: "VOTING" },
  { nama: "Muhammad Rizky Oktavianda", password: "VOTING" },
  { nama: "Nabila Adiska", password: "VOTING" },
  { nama: "Nayla Nabila", password: "VOTING" },
  { nama: "Nur Annisa Syawalia", password: "VOTING" },
  { nama: "Oktavian Suseno", password: "VOTING" },
  { nama: "Pramezwari Azzahra Keisya Ganafiqa", password: "VOTING" },
  { nama: "Rasya Ananta Islami", password: "VOTING" },
  { nama: "Risky Aryanto", password: "VOTING" },
  { nama: "Shelya Nova Wandari", password: "VOTING" },
  { nama: "Siti Zasmin", password: "VOTING" },
  { nama: "Siti Faras Nur Hafizah", password: "VOTING" },
  { nama: "Tisya Lovely  Azzahira", password: "VOTING" },
  { nama: "Waradana Aryasetya", password: "VOTING" },
  // Kelas XI B (dahulu Kelas XB)
  { nama: "Alycia Putri", password: "VOTING" },
  { nama: "Arya Rachman", password: "VOTING" },
  { nama: "Aulia Calista", password: "VOTING" },
  { nama: "Awzia Aprianti", password: "VOTING" },
  { nama: "Bintang Akmal Putra", password: "VOTING" },
  { nama: "Cintami Sabrina Putri", password: "VOTING" },
  { nama: "Dheanove Putri Chalissa", password: "VOTING" },
  { nama: "Dina Amalia", password: "VOTING" },
  { nama: "Fariz Prasetyo", password: "VOTING" },
  { nama: "Fazar Azhari", password: "VOTING" },
  { nama: "Fiqri Febrian", password: "VOTING" },
  { nama: "Hafy Setia Raqilla", password: "VOTING" },
  { nama: "Intan Novianti", password: "VOTING" },
  { nama: "Khalishah Farah Ashilah", password: "VOTING" },
  { nama: "Melly Tattiya Nova", password: "VOTING" },
  { nama: "Muhammad Azka Aditya Zaki", password: "VOTING" },
  { nama: "Muhammad Chairul", password: "VOTING" },
  { nama: "Muhammad Diaz Rana Cavalero", password: "VOTING" },
  { nama: "Muhammad Fadhil", password: "VOTING" },
  { nama: "Muhammad Farrell Akbar", password: "VOTING" },
  { nama: "M. Nazriel  Maulana", password: "VOTING" },
  { nama: "Muhammad Khalid Abdillah", password: "VOTING" },
  { nama: "Nadien Salsabillah Natasyah", password: "VOTING" },
  { nama: "Najwa Nadhira Zahra", password: "VOTING" },
  { nama: "Nazwa Al Mira Alzahra", password: "VOTING" },
  { nama: "Niki Alfathir", password: "VOTING" },
  { nama: "Nova Ariani", password: "VOTING" },
  { nama: "Quinnzha Ernesta Syaffarani", password: "VOTING" },
  { nama: "Rasyya Fathian Nuha", password: "VOTING" },
  { nama: "Ridho Kurniawan", password: "VOTING" },
  { nama: "Salshabila Ulaya Rizk", password: "VOTING" },
  { nama: "Saskia Dwi Aprilian", password: "VOTING" },
  { nama: "Syarif Rafif Mudzaki", password: "VOTING" },
  { nama: "Tahta Lailatul Putri Hendrawan", password: "VOTING" },
  { nama: "Vikry Mauriansyah", password: "VOTING" },
  { nama: "Vina Sazwari", password: "VOTING" },
  // Kelas XI C (dahulu Kelas XC)
  { nama: "Aditya Pratama Putra", password: "VOTING" },
  { nama: "Agmeil Suci Rahmadani", password: "VOTING" },
  { nama: "Azrilia Shakira Alfarista", password: "VOTING" },
  { nama: "Dhika Amrullah", password: "VOTING" },
  { nama: "Donita Jonas", password: "VOTING" },
  { nama: "Duta Mahardika", password: "VOTING" },
  { nama: "Erdhio Dhaffa Alfarezi", password: "VOTING" },
  { nama: "Febriani Satipah", password: "VOTING" },
  { nama: "Galang Raffa Aydil Fitra", password: "VOTING" },
  { nama: "Geogrepanto", password: "VOTING" },
  { nama: "Julio Ceasar Marpaung", password: "VOTING" },
  { nama: "Kayla Hartika", password: "VOTING" },
  { nama: "Maya Arsita", password: "VOTING" },
  { nama: "Muhammad Galih Herdi Nugraha", password: "VOTING" },
  { nama: "Muhammad Rabuansyah", password: "VOTING" },
  { nama: "Muhammad Rizki", password: "VOTING" },
  { nama: "Najla Khaliishah Khayriyah", password: "VOTING" },
  { nama: "Nayla Aprilia", password: "VOTING" },
  { nama: "Noval Basim Nur", password: "VOTING" },
  { nama: "Nurani Kayla Rahmania", password: "VOTING" },
  { nama: "Rafa Ilhamsyah", password: "VOTING" },
  { nama: "Rafie Ilham Febryan", password: "VOTING" },
  { nama: "Rasyiqah Hazirah", password: "VOTING" },
  { nama: "Raya Tri Gelion", password: "VOTING" },
  { nama: "Ria Rahmah", password: "VOTING" },
  { nama: "Rifa Aleesya Idaya", password: "VOTING" },
  { nama: "Riny Lestary", password: "VOTING" },
  { nama: "Salmi Novriani", password: "VOTING" },
  { nama: "Sari Wahdania", password: "VOTING" },
  { nama: "Syafitasari Azzahra", password: "VOTING" },
  { nama: "Syapitri Anggrainy", password: "VOTING" },
  { nama: "Syarif Muhammad Abdul Fathir", password: "VOTING" },
  { nama: "Syarif Muhammad Fathir Faruqi", password: "VOTING" },
  { nama: "Tri Anugrah Septianto", password: "VOTING" },
  { nama: "Vino Yuichi Hermawan", password: "VOTING" },
  { nama: "Zulfa Alivia Ananda", password: "VOTING" },
  // Kelas XI D (dahulu Kelas XD)
  { nama: "Abdul Rahman", password: "VOTING" },
  { nama: "Alif Andromeda Friendly", password: "VOTING" },
  { nama: "Anissa Sabita", password: "VOTING" },
  { nama: "Aulisa Novemy", password: "VOTING" },
  { nama: "Balisqa Rayavinara", password: "VOTING" },
  { nama: "Bella Safira", password: "VOTING" },
  { nama: "Daffa Anugrah", password: "VOTING" },
  { nama: "Dian Yang Tak Kunjung Padam", password: "VOTING" },
  { nama: "Elisa Juniarti Prana", password: "VOTING" },
  { nama: "Fajar Muflih", password: "VOTING" },
  { nama: "Gerardus Fino Panampe", password: "VOTING" },
  { nama: "Gilang Bintang Pratama", password: "VOTING" },
  { nama: "Kayla Naviza", password: "VOTING" },
  { nama: "Khairunnisa Khabila", password: "VOTING" },
  { nama: "Laila Novianti", password: "VOTING" },
  { nama: "Melly Dwi Lestari", password: "VOTING" },
  { nama: "Muhammad Abyan Prameswara", password: "VOTING" },
  { nama: "Muhammad Aqila", password: "VOTING" },
  { nama: "Muhammad Azri Hidayat", password: "VOTING" },
  { nama: "Muhammad Rifqi Dwi Cahyo", password: "VOTING" },
  { nama: "Mulyadi Saputra", password: "VOTING" },
  { nama: "Muslimah Lila Febrianti", password: "VOTING" },
  { nama: "Nazwa Aulia", password: "VOTING" },
  { nama: "Pratiwi Septiana", password: "VOTING" },
  { nama: "Putri Nayka Sukma", password: "VOTING" },
  { nama: "Putri Suci Maulidya", password: "VOTING" },
  { nama: "Raffa Naufal Supriyadi", password: "VOTING" },
  { nama: "Rhaditya Pratama", password: "VOTING" },
  { nama: "Rizky Anugrah Pratama", password: "VOTING" },
  { nama: "Rizqullah Destro Helno Hariyanto", password: "VOTING" },
  { nama: "Ryu Taubatan", password: "VOTING" },
  { nama: "Safa Nabila Rizkullah", password: "VOTING" },
  { nama: "Salma Batsinatul Adilah", password: "VOTING" },
  { nama: "Syarif Muhammad Rifki Fadhilah", password: "VOTING" },
  { nama: "Vellent Nazwa Alesya", password: "VOTING" },
  { nama: "Zero Aurion Marthen", password: "VOTING" },
  // Kelas XI E (dahulu Kelas XE)
  { nama: "Aditya Yoga Pratama", password: "VOTING" },
  { nama: "Ahmad Zouhri Nasution", password: "VOTING" },
  { nama: "Aletta Laverda Zahra", password: "VOTING" },
  { nama: "Amelya Maharani", password: "VOTING" },
  { nama: "Arkan Attaya", password: "VOTING" },
  { nama: "Azlea Zanaya", password: "VOTING" },
  { nama: "Berwin Sandha Prawara", password: "VOTING" },
  { nama: "Bian Mahesya", password: "VOTING" },
  { nama: "Caprillia Sanaz Putri", password: "VOTING" },
  { nama: "Ciko Alfiansyah", password: "VOTING" },
  { nama: "Dewi Amalia Maulani", password: "VOTING" },
  { nama: "Fadhil Dwi Mulya", password: "VOTING" },
  { nama: "Faturrahman Abu Rizal Sarfaras", password: "VOTING" },
  { nama: "Fhanesa Ashy Stiva Permata Fima", password: "VOTING" },
  { nama: "Gusti Muhammad Aditya", password: "VOTING" },
  { nama: "Hafizh Hanif Alhakim", password: "VOTING" },
  { nama: "Haikal Rifqi Rabbani", password: "VOTING" },
  { nama: "Muhammad Albani Amalfi", password: "VOTING" },
  { nama: "Muhammad Rakha Altav", password: "VOTING" },
  { nama: "Muhammad Raya Milan Ramadhan", password: "VOTING" },
  { nama: "Muhammad Syakil Althaf", password: "VOTING" },
  { nama: "Muhammad Zainal Abidin Maysa Putra", password: "VOTING" },
  { nama: "Namira Rana Meutia", password: "VOTING" },
  { nama: "Nur Salam", password: "VOTING" },
  { nama: "Qanita Khairunnisa", password: "VOTING" },
  { nama: "Raffi Nawarul Huda", password: "VOTING" },
  { nama: "Reyhan Febriano", password: "VOTING" },
  { nama: "Riski Otaviani", password: "VOTING" },
  { nama: "Salma Novriani", password: "VOTING" },
  { nama: "Salwa Humairah", password: "VOTING" },
  { nama: "Sistania Syadza Al Athira", password: "VOTING" },
  { nama: "Syaafa Aulia Putri Ramadhani", password: "VOTING" },
  { nama: "Syarifah Nadilla Assegaf", password: "VOTING" },
  { nama: "Syifa Miftahul Jannah", password: "VOTING" },
  { nama: "Wulandini Okthafia", password: "VOTING" },
  { nama: "Zaky Alfatih Ramadhani", password: "VOTING" },
  // Kelas XI F (dahulu Kelas XF)
  { nama: "Adam Maulana", password: "VOTING" },
  { nama: "Ahmad Tubir", password: "VOTING" },
  { nama: "Alhadi Maulandari", password: "VOTING" },
  { nama: "Anugrah Ramadhan Putra Niko Prasetyo", password: "VOTING" },
  { nama: "Aura Meilin Tazkia", password: "VOTING" },
  { nama: "Ayu Diah Novianti", password: "VOTING" },
  { nama: "Azzahra Athariyah Balqiz", password: "VOTING" },
  { nama: "Bayu Ramadhan Wirabuana", password: "VOTING" },
  { nama: "Beby Ayu Nur Aini", password: "VOTING" },
  { nama: "Bella Yuniarti", password: "VOTING" },
  { nama: "Bilal Fachri Albani", password: "VOTING" },
  { nama: "Daffa Annauval Rashieka", password: "VOTING" },
  { nama: "Desya Aprianti", password: "VOTING" },
  { nama: "Ervina Roliansyah Putri", password: "VOTING" },
  { nama: "Hidayatu Fatimah", password: "VOTING" },
  { nama: "Karin Permatasari", password: "VOTING" },
  { nama: "Khairil Imam Hanafi", password: "VOTING" },
  { nama: "Melvan Davana Putra", password: "VOTING" },
  { nama: "Muhammad Azril Arkan Ardani", password: "VOTING" },
  { nama: "Muhammad Dzaki Audani", password: "VOTING" },
  { nama: "Muhammad Fahtir A'sari", password: "VOTING" },
  { nama: "Muhammad Fathir Vandra Wiratama", password: "VOTING" },
  { nama: "Muhammadun Daiman", password: "VOTING" },
  { nama: "Najwa Magdalena", password: "VOTING" },
  { nama: "Nasya Putri Aulia", password: "VOTING" },
  { nama: "Naufal Fadhil Muhammad", password: "VOTING" },
  { nama: "Nova Safitri", password: "VOTING" },
  { nama: "Nuraini", password: "VOTING" },
  { nama: "Radit", password: "VOTING" },
  { nama: "Ramadhani Alsis", password: "VOTING" },
  { nama: "Reno Gumlar", password: "VOTING" },
  { nama: "Rifail Restu Andika", password: "VOTING" },
  { nama: "Rizky Yunior Alfiansyah", password: "VOTING" },
  { nama: "Syf Faizah", password: "VOTING" },
  { nama: "Syifa Azhura Salsabila", password: "VOTING" },
  { nama: "Veby Cahaya Intani", password: "VOTING" },
  // Kelas XII A
  { nama: "Achmad Bima Cahyono", password: "VOTING" },
  { nama: "Aisyah Adzani Khairunisa", password: "VOTING" },
  { nama: "Alif Nauval Muzzaki", password: "VOTING" },
  { nama: "Alya Fayza Fahriya", password: "VOTING" },
  { nama: "Amanda Auliya", password: "VOTING" },
  { nama: "Andhika Prasetyo", password: "VOTING" },
  { nama: "Andi Reval Zohir", password: "VOTING" },
  { nama: "Anisya Avrillya Yudha", password: "VOTING" },
  { nama: "Aqila Al-Fadhilah", password: "VOTING" },
  { nama: "Azril Ardiansyah Febriyanto", password: "VOTING" },
  { nama: "Chantika Bella", password: "VOTING" },
  { nama: "Dhea Zaskia", password: "VOTING" },
  { nama: "Farras Aprinindy", password: "VOTING" },
  { nama: "Fikri Yusra Dafa", password: "VOTING" },
  { nama: "Flora Thiana", password: "VOTING" },
  { nama: "Gabriel De Marco", password: "VOTING" },
  { nama: "Gita Dwi Ardianti", password: "VOTING" },
  { nama: "Ibrahimovic", password: "VOTING" },
  { nama: "Imam Ar Rasyid", password: "VOTING" },
  { nama: "Indah Nuraini", password: "VOTING" },
  { nama: "Intan Nuril Aulia", password: "VOTING" },
  { nama: "Jonathan Sugito", password: "VOTING" },
  { nama: "Kezia Triastuti", password: "VOTING" },
  { nama: "Khaalishah Rayya", password: "VOTING" },
  { nama: "Malaika Bilqis", password: "VOTING" },
  { nama: "Muhammad Khalilullah", password: "VOTING" },
  { nama: "Najwa Aulia Natasha", password: "VOTING" },
  { nama: "Raisha Anindia Putri", password: "VOTING" },
  { nama: "Restisia Rinjani", password: "VOTING" },
  { nama: "Revha Varas Nurdianti", password: "VOTING" },
  { nama: "Rica Ariyanti Putri Irawan", password: "VOTING" },
  { nama: "Ryanthi Nayla Azzahra Syadina", password: "VOTING" },
  { nama: "Sonia Herzegovina", password: "VOTING" },
  { nama: "Syarifah Fiani", password: "VOTING" },
  { nama: "Zahwa Zahira", password: "VOTING" },
  { nama: "Zalikha Aura Fajriya", password: "VOTING" },
  // Kelas XII B
  { nama: "Afriliawati Ningrum", password: "VOTING" },
  { nama: "Aira Syafifa Nabila", password: "VOTING" },
  { nama: "Alya Nafilah", password: "VOTING" },
  { nama: "Ananda Widyani", password: "VOTING" },
  { nama: "Anisa Wulan Safira", password: "VOTING" },
  { nama: "Annisa Nurul Hikmah", password: "VOTING" },
  { nama: "Annisa Raudhatuljannah", password: "VOTING" },
  { nama: "Arini Gebry Maqfiroh", password: "VOTING" },
  { nama: "Arvia Hernanda", password: "VOTING" },
  { nama: "Danis Dwi Prasetya", password: "VOTING" },
  { nama: "Dini Anggraini", password: "VOTING" },
  { nama: "Eda Adalia Dauzan", password: "VOTING" },
  { nama: "Fidia Humairo", password: "VOTING" },
  { nama: "Firza Resdiana Adi Sasxiya P", password: "VOTING" },
  { nama: "Ghina Izzati Ulya", password: "VOTING" },
  { nama: "Khalisha Mardhatilah", password: "VOTING" },
  { nama: "Kirana Mecca", password: "VOTING" },
  { nama: "Marsya Maulidya", password: "VOTING" },
  { nama: "Muhammad Bily Akbar", password: "VOTING" },
  { nama: "Muhammad Dio Alief Pratama", password: "VOTING" },
  { nama: "Muhammad Dzulfikar Rahman", password: "VOTING" },
  { nama: "Muhammad Fadhil Pratama", password: "VOTING" },
  { nama: "Muhammad Farrel Hartanto", password: "VOTING" },
  { nama: "Muhammad Naufal Ridho", password: "VOTING" },
  { nama: "Najla Putri Purnomo", password: "VOTING" },
  { nama: "Nisfu Syakban", password: "VOTING" },
  { nama: "Rachel Gracia", password: "VOTING" },
  { nama: "Rafa Fairuz Ramadhan", password: "VOTING" },
  { nama: "Raja Doli Paruhum Harahap", password: "VOTING" },
  { nama: "Refi Naufal Ikbar", password: "VOTING" },
  { nama: "Satrio Rizky Pratama", password: "VOTING" },
  { nama: "Shinta Shintia Maharani", password: "VOTING" },
  { nama: "Syarifah Moulidya Fhatimah", password: "VOTING" },
  { nama: "Syavinatu Zahrani", password: "VOTING" },
  { nama: "Weni Puji Apriliani", password: "VOTING" },
  { nama: "Yuliana Nur Aini", password: "VOTING" },
  // Kelas XII C
  { nama: "Aisyah", password: "VOTING" },
  { nama: "Akmal Al Dzaki Septiansyah", password: "VOTING" },
  { nama: "Amirah Nur Sabrina", password: "VOTING" },
  { nama: "Chryztiano Johanes Tryztan Doki", password: "VOTING" },
  { nama: "Clarinda Daffa Artanovia", password: "VOTING" },
  { nama: "Dika Satria", password: "VOTING" },
  { nama: "Fachry Wahyufi", password: "VOTING" },
  { nama: "Farrel Mahendra Pratama", password: "VOTING" },
  { nama: "Fasya Pratama", password: "VOTING" },
  { nama: "Fayyadh Rifqi Muhammad", password: "VOTING" },
  { nama: "Laurensius Denis", password: "VOTING" },
  { nama: "M.Riziq Hastama Subrata", password: "VOTING" },
  { nama: "Muhammad Arkazora Nugraha", password: "VOTING" },
  { nama: "Muhammad Erick Alifio", password: "VOTING" },
  { nama: "Muhammad Farel Akbar", password: "VOTING" },
  { nama: "Mohammad Haydar Sharim Athala", password: "VOTING" },
  { nama: "Muhammad Imam Ghazali", password: "VOTING" },
  { nama: "Muhammad Izzan Gustamir", password: "VOTING" },
  { nama: "Muhammad Yusuf Salim", password: "VOTING" },
  { nama: "Nabil Alifuddin Pajokka", password: "VOTING" },
  { nama: "Nadia Julissa", password: "VOTING" },
  { nama: "Nadiah Elvaretta Azarine", password: "VOTING" },
  { nama: "Nayla Kirana", password: "VOTING" },
  { nama: "Neval Milito Bernata", password: "VOTING" },
  { nama: "Raihan Aly Wicaksono", password: "VOTING" },
  { nama: "Rafif Auffahryzal", password: "VOTING" },
  { nama: "Rania Mochsin Attamimi", password: "VOTING" },
  { nama: "Rayhan Ridho Pasha", password: "VOTING" },
  { nama: "Rini Anjani", password: "VOTING" },
  { nama: "Rizky Alfandi", password: "VOTING" },
  { nama: "Satrio Wiradithya Assidikqi", password: "VOTING" },
  { nama: "Thalita Noza Al Zena", password: "VOTING" },
  { nama: "Veli Paria Putri", password: "VOTING" },
  { nama: "Vella Cancerya", password: "VOTING" },
  { nama: "Wini Aprilia Azahra", password: "VOTING" },
  { nama: "Wulandari", password: "VOTING" },
  // Kelas XII D
  { nama: "Abdul Aziz Aufa", password: "VOTING" },
  { nama: "Adeliani Brilianti Aisyah Putri", password: "VOTING" },
  { nama: "Adityo Nugroho", password: "VOTING" },
  { nama: "Ambo Reyga Putra Viandi", password: "VOTING" },
  { nama: "Andi Navygo  Tirtayasa", password: "VOTING" },
  { nama: "Arlie Fitri Jatiningrum", password: "VOTING" },
  { nama: "Bintang Junior", password: "VOTING" },
  { nama: "Devi Sariyan Dani", password: "VOTING" },
  { nama: "Dhabita Nazirah Aura Danie", password: "VOTING" },
  { nama: "Elvira Fitriani", password: "VOTING" },
  { nama: "Faiz Triyadi Ilham", password: "VOTING" },
  { nama: "Farhan Syahputra", password: "VOTING" },
  { nama: "Fathir Ramadhan", password: "VOTING" },
  { nama: "Ibnu Atthahilla", password: "VOTING" },
  { nama: "Kumalaretno Candradewi Pusitasari", password: "VOTING" },
  { nama: "Luthfi Athaullah", password: "VOTING" },
  { nama: "Mega Aulia Sari", password: "VOTING" },
  { nama: "Muhammad Firza Hidayatullah", password: "VOTING" },
  { nama: "Muhammad Aqsha", password: "VOTING" },
  { nama: "Muhammad Rafli", password: "VOTING" },
  { nama: "Muhammad Revi Saputra", password: "VOTING" },
  { nama: "Muhammad Rizky Syahputra", password: "VOTING" },
  { nama: "Mutiya Kurniasih", password: "VOTING" },
  { nama: "Nadya Mahmudah", password: "VOTING" },
  { nama: "Naufal Daffa Denaldi", password: "VOTING" },
  { nama: "Nur Rachmad Sugiarto", password: "VOTING" },
  { nama: "Oshea Evanda Pratama", password: "VOTING" },
  { nama: "Rajiy Fahri Rasya", password: "VOTING" },
  { nama: "Rasya Azfa Aulia", password: "VOTING" },
  { nama: "Reiky Arkan Al Ghazy", password: "VOTING" },
  { nama: "Rizky Kurniawan", password: "VOTING" },
  { nama: "Salim Rosyad", password: "VOTING" },
  { nama: "Syarifah Maudy Aprilia Hasanah", password: "VOTING" },
  { nama: "Zikri Maulana", password: "VOTING" },
  { nama: "Apri Pratiwi", password: "VOTING" },
  // Kelas XII E
  { nama: "Adam Febrian", password: "VOTING" },
  { nama: "Afifah Nuriandari", password: "VOTING" },
  { nama: "Assifa Kinaya Putri", password: "VOTING" },
  { nama: "Azwar Sadikin", password: "VOTING" },
  { nama: "Dani Christian", password: "VOTING" },
  { nama: "Diah Ayu Setia Ningrum", password: "VOTING" },
  { nama: "Dita Amelia", password: "VOTING" },
  { nama: "Fachril Putra Yuandra", password: "VOTING" },
  { nama: "Fahri Rizqullah", password: "VOTING" },
  { nama: "Farhan Muzakki Saputra", password: "VOTING" },
  { nama: "Farhan Wirandanu", password: "VOTING" },
  { nama: "Fitri Yani", password: "VOTING" },
  { nama: "Gading Firmansyah", password: "VOTING" },
  { nama: "Gavin", password: "VOTING" },
  { nama: "Hery Irawan Candra", password: "VOTING" },
  { nama: "Hilyah Almaas Nafisah Ghassani", password: "VOTING" },
  { nama: "Immanuel", password: "VOTING" },
  { nama: "Intan Audy", password: "VOTING" },
  { nama: "Juwita Arta Ningrum", password: "VOTING" },
  { nama: "Kafi Rijal Trystan", password: "VOTING" },
  { nama: "Keyza Pasha Ramadhan", password: "VOTING" },
  { nama: "Lukmanul Hakim", password: "VOTING" },
  { nama: "Meisya Herwika", password: "VOTING" },
  { nama: "Melati", password: "VOTING" },
  { nama: "Muhammad Helmi Fayyadhi Al Parisi", password: "VOTING" },
  { nama: "Muhammad Rizki Ramadhan", password: "VOTING" },
  { nama: "Muhammad Syafiran", password: "VOTING" },
  { nama: "Nela Savitry", password: "VOTING" },
  { nama: "Quinsa Arafansa", password: "VOTING" },
  { nama: "Rakha Almer Badila Rabbani", password: "VOTING" },
  { nama: "Ramzi Maulana", password: "VOTING" },
  { nama: "Ririn Apriyanti", password: "VOTING" },
  { nama: "Syahira Yudha Azalea", password: "VOTING" },
  { nama: "Tan Natasya Khairunisa", password: "VOTING" },
  { nama: "Thomas Antares", password: "VOTING" },
  { nama: "Zhidane Yudistira", password: "VOTING" },
  // Kelas XII F
  { nama: "Aditya", password: "VOTING" },
  { nama: "Adrias Periwanto", password: "VOTING" },
  { nama: "Afa Muhammad Sugiharto", password: "VOTING" },
  { nama: "Afifah Putri Alifia", password: "VOTING" },
  { nama: "Ahmad Try Bagas Ismail", password: "VOTING" },
  { nama: "Alvano Ziven Raditya Ramadhan", password: "VOTING" },
  { nama: "Andra Fadilah", password: "VOTING" },
  { nama: "Anugrah Putra Pratama", password: "VOTING" },
  { nama: "Arif Arahman", password: "VOTING" },
  { nama: "Avrina Khairunisa", password: "VOTING" },
  { nama: "Charin Damayanti", password: "VOTING" },
  { nama: "Cika Rahayu", password: "VOTING" },
  { nama: "Ella Rahmadhani", password: "VOTING" },
  { nama: "Fajar Saputra", password: "VOTING" },
  { nama: "Hidayattullah", password: "VOTING" },
  { nama: "Iqbal Ababiel", password: "VOTING" },
  { nama: "Julita", password: "VOTING" },
  { nama: "Keannu Hita Athalla", password: "VOTING" },
  { nama: "Kholilurrahman", password: "VOTING" },
  { nama: "M. Guruh Vredley Kalalembang", password: "VOTING" },
  { nama: "Mudrika Maharani Putri", password: "VOTING" },
  { nama: "Muhamad Atagavi Abrar", password: "VOTING" },
  { nama: "Muhammad Kharis Gunawan", password: "VOTING" },
  { nama: "Muhammad Rofi Akmal", password: "VOTING" },
  { nama: "Muhammad Syafiq", password: "VOTING" },
  { nama: "Nabil Hafidz", password: "VOTING" },
  { nama: "Nadhifa Khansa", password: "VOTING" },
  { nama: "Nuraini Fauziah", password: "VOTING" },
  { nama: "Parman", password: "VOTING" },
  { nama: "Raditya Revan Akbar", password: "VOTING" },
  { nama: "Rara Dwi Anggira", password: "VOTING" },
  { nama: "Ratih Lucky", password: "VOTING" },
  { nama: "Rayhan Anggara", password: "VOTING" },
  { nama: "Siti Zaitun Arini", password: "VOTING" },
  { nama: "Yulis Amelia", password: "VOTING" },
  // Kelas X A
  { nama: "Abimayu Umarrai", password: "VOTING" },
  { nama: "Adli Putra Pratama", password: "VOTING" },
  { nama: "Alesha Guenna Santoso", password: "VOTING" },
  { nama: "Alifiah Salsabila Syarwani", password: "VOTING" },
  { nama: "Amira Dasyha Rifani", password: "VOTING" },
  { nama: "Aqmal Syafareza", password: "VOTING" },
  { nama: "Aulia Nur Ikhsan", password: "VOTING" },
  { nama: "Dimas Azri", password: "VOTING" },
  { nama: "Dita Salsabilla", password: "VOTING" },
  { nama: "Farouk Zulfakar", password: "VOTING" },
  { nama: "Fildzah Zahirah Nabiihah", password: "VOTING" },
  { nama: "Gina Haura Dzakiah", password: "VOTING" },
  { nama: "Irfan Barry Muchairil", password: "VOTING" },
  { nama: "Irtiza Julian", password: "VOTING" },
  { nama: "Irvan Herfian", password: "VOTING" },
  { nama: "Julham", password: "VOTING" },
  { nama: "Khairan Zaidan Pradita", password: "VOTING" },
  { nama: "Muhamad Teguh", password: "VOTING" },
  { nama: "Muhammad Algedzra Alkadrie", password: "VOTING" },
  { nama: "Muhammad Arfan Altamis", password: "VOTING" },
  { nama: "Muhammad Ataillah Jaya Riqh Adevka", password: "VOTING" },
  { nama: "Muhammad Nafis Ilham", password: "VOTING" },
  { nama: "Muhammad Vito Aldryan", password: "VOTING" },
  { nama: "Nazlyla Khanza Zuneta", password: "VOTING" },
  { nama: "Nur'ain", password: "VOTING" },
  { nama: "Qalbi Rahmana", password: "VOTING" },
  { nama: "Qieran Quranisya Al Islami Putri", password: "VOTING" },
  { nama: "Radit Destriantoro", password: "VOTING" },
  { nama: "Ragil Dzaka Satrio", password: "VOTING" },
  { nama: "Rifqi Aunur Rahman", password: "VOTING" },
  { nama: "Rizka Nafeeza", password: "VOTING" },
  { nama: "Rustinah Sari", password: "VOTING" },
  { nama: "Syakila Khairunnisa", password: "VOTING" },
  { nama: "Syakirah Fertiwi Hutasuhut", password: "VOTING" },
  { nama: "Syarifa Andinie", password: "VOTING" },
  { nama: "Tri Suci Maharani", password: "VOTING" },
  // Kelas X B
  { nama: "Adhelila Nur Ramadhani", password: "VOTING" },
  { nama: "Chiko Azka Maulana", password: "VOTING" },
  { nama: "Dwi Syifa Rahmawati", password: "VOTING" },
  { nama: "Fadhil Faturrusy", password: "VOTING" },
  { nama: "Fakhriyyah Ukhti Fillah", password: "VOTING" },
  { nama: "Kayla Ayudia Safira", password: "VOTING" },
  { nama: "Kesha Dilanu Athillah", password: "VOTING" },
  { nama: "Kharifa Putri Saleha", password: "VOTING" },
  { nama: "M. Rio Saputra Pradana", password: "VOTING" },
  { nama: "Muhamad Antoni Mulyawan", password: "VOTING" },
  { nama: "Muhammad Azriel Maulana", password: "VOTING" },
  { nama: "Muhammad Daffasha Ramadhan", password: "VOTING" },
  { nama: "Muhammad Fauzy Juansyah", password: "VOTING" },
  { nama: "Muhammad Stieven Iqbal", password: "VOTING" },
  { nama: "Muhammad Zaffa Abrar", password: "VOTING" },
  { nama: "Nabila Aprilia", password: "VOTING" },
  { nama: "Nazarul Ihsan Pratama", password: "VOTING" },
  { nama: "Nova Aurelia", password: "VOTING" },
  { nama: "Nur Fatiha Chairunnisa", password: "VOTING" },
  { nama: "Nur'aini", password: "VOTING" },
  { nama: "Raffa Julio Maulana", password: "VOTING" },
  { nama: "Rafi Akmal Syakieb", password: "VOTING" },
  { nama: "Rasyah Rahmat Tullah", password: "VOTING" },
  { nama: "Redha Pradikca", password: "VOTING" },
  { nama: "Resty Octaviani", password: "VOTING" },
  { nama: "Riezky Rezzi Ananta", password: "VOTING" },
  { nama: "Robby Mutazzidan Daud", password: "VOTING" },
  { nama: "Salsabilah Alifah Ardian", password: "VOTING" },
  { nama: "Satrio Akbar Maulana", password: "VOTING" },
  { nama: "Septi Nur Faidah", password: "VOTING" },
  { nama: "Shafa Maritza", password: "VOTING" },
  { nama: "Sultan Halim Aprilio", password: "VOTING" },
  { nama: "Syarifah Nabillah", password: "VOTING" },
  { nama: "Tegar Indi Pratama", password: "VOTING" },
  { nama: "Uray Aurelia Fayza Almira", password: "VOTING" },
  { nama: "Zahy Fathin Fadhilah", password: "VOTING" },
  // Kelas X C
  { nama: "Adrianus", password: "VOTING" },
  { nama: "Afifa Aprilya Putri", password: "VOTING" },
  { nama: "Alissa Inayyah Azzahra", password: "VOTING" },
  { nama: "Amira Nabiilah Rusdi", password: "VOTING" },
  { nama: "Aquirilla Rahmadani Winata", password: "VOTING" },
  { nama: "Assyifa Zaira Ramadhani", password: "VOTING" },
  { nama: "Dinul Habib Akhbariansyah", password: "VOTING" },
  { nama: "Fachri Meidian Zuchri", password: "VOTING" },
  { nama: "Fakhir Faizan Al Fikri", password: "VOTING" },
  { nama: "Farel Febrian", password: "VOTING" },
  { nama: "Hanifah Fitri", password: "VOTING" },
  { nama: "Khiara Alfina Putri", password: "VOTING" },
  { nama: "Marwah Sakbarianty", password: "VOTING" },
  { nama: "Muhammad Danis", password: "VOTING" },
  { nama: "Muhammad Fadilkhan", password: "VOTING" },
  { nama: "Muhammad Huzaifah Al Ashri Marsuri", password: "VOTING" },
  { nama: "Muhammad Ilham", password: "VOTING" },
  { nama: "Muhammad Nur Akmal", password: "VOTING" },
  { nama: "Muhammad Raymond Syafiq", password: "VOTING" },
  { nama: "Muhammad Rich Keanu Reeves", password: "VOTING" },
  { nama: "Muhammad Syairosi", password: "VOTING" },
  { nama: "Naufal Akmal Azizi", password: "VOTING" },
  { nama: "Nimas Cahya Tias", password: "VOTING" },
  { nama: "Putra Aditya", password: "VOTING" },
  { nama: "Raden Dion Gilang Prakoso Elias", password: "VOTING" },
  { nama: "Rizki Putra Pratama", password: "VOTING" },
  { nama: "Reyhana", password: "VOTING" },
  { nama: "Sandy Aulian", password: "VOTING" },
  { nama: "Shofi Aghla Salsabil", password: "VOTING" },
  { nama: "Siti Nurpadilah", password: "VOTING" },
  { nama: "Suci Rahmawati", password: "VOTING" },
  { nama: "Umar Al Faruq", password: "VOTING" },
  { nama: "Unaisyah", password: "VOTING" },
  { nama: "Varisha Nazwa", password: "VOTING" },
  { nama: "Vita Aurelia Lestari", password: "VOTING" },
  { nama: "Zaahir Rizki Zhuherlan", password: "VOTING" },
  // Kelas X D
  { nama: "Aira Dwi Rizky", password: "VOTING" },
  { nama: "Akbar Saputra Perdana", password: "VOTING" },
  { nama: "Allbi Akbar Darmawan", password: "VOTING" },
  { nama: "Amalia Siti Umairoh", password: "VOTING" },
  { nama: "Chelsi Mutiara Kasih", password: "VOTING" },
  { nama: "Deswara Naufal Aditya", password: "VOTING" },
  { nama: "Faeyza Arman", password: "VOTING" },
  { nama: "Fellix Jerrycho", password: "VOTING" },
  { nama: "Gabriela Emirah Maharani", password: "VOTING" },
  { nama: "Haikal Nur Hanif", password: "VOTING" },
  { nama: "Ibrahim Menza Arkana", password: "VOTING" },
  { nama: "Janeeta Aulia Ramadhani", password: "VOTING" },
  { nama: "Jihan Az Zahra", password: "VOTING" },
  { nama: "Joenathan Situmorang", password: "VOTING" },
  { nama: "Kristiano Febrian", password: "VOTING" },
  { nama: "Lailatul Fizriah", password: "VOTING" },
  { nama: "Liejensen", password: "VOTING" },
  { nama: "Muhammad Difatriyadi Mobarok Ramadhan", password: "VOTING" },
  { nama: "Myiesha Nafeeza Ayu", password: "VOTING" },
  { nama: "Nicon Darius Lase", password: "VOTING" },
  { nama: "Niken Azka Lafatunnisa", password: "VOTING" },
  { nama: "Nurhasana", password: "VOTING" },
  { nama: "Nurulia Aldanersa", password: "VOTING" },
  { nama: "Rafiul Al Kibriya", password: "VOTING" },
  { nama: "Rizky Adam", password: "VOTING" },
  { nama: "Sekar Wahyu Putrini", password: "VOTING" },
  { nama: "Siti Ramadhani", password: "VOTING" },
  { nama: "Sui Min", password: "VOTING" },
  { nama: "Syaffa Sakbaniar", password: "VOTING" },
  { nama: "Syarif Albasil Azhallah Runi Alidrus", password: "VOTING" },
  { nama: "Syarif Aydin Aqila", password: "VOTING" },
  { nama: "Tiara Nur Islami", password: "VOTING" },
  { nama: "Vela Risa Angeline", password: "VOTING" },
  { nama: "Zaki Akmal", password: "VOTING" },
  { nama: "Zalfa Nathania Syahla", password: "VOTING" },
  { nama: "Zein Ghanie Elhamdaniy", password: "VOTING" },
  // Kelas X E
  { nama: "Abio Novanka Azzmy", password: "VOTING" },
  { nama: "Aini Thahirah", password: "VOTING" },
  { nama: "Alfin Maulana Akbar", password: "VOTING" },
  { nama: "Alifah Kiyah Syahwa", password: "VOTING" },
  { nama: "Annita Fitria Sulistiana", password: "VOTING" },
  { nama: "Azam Firmansyah", password: "VOTING" },
  { nama: "Azril Afzanizam", password: "VOTING" },
  { nama: "Chelsea", password: "VOTING" },
  { nama: "Desria Nurri", password: "VOTING" },
  { nama: "Dharren Wilie Perdana", password: "VOTING" },
  { nama: "Farhana Azalia", password: "VOTING" },
  { nama: "Faris Khoiril Murtadho", password: "VOTING" },
  { nama: "Gitta Kirana", password: "VOTING" },
  { nama: "Hanan Fauzan Kurniawan", password: "VOTING" },
  { nama: "Iqbal Maulana", password: "VOTING" },
  { nama: "Kenzo Aryasa Anugerah Pratama", password: "VOTING" },
  { nama: "Lazaru Al Barca", password: "VOTING" },
  { nama: "Mas Nizar Athaurrahman", password: "VOTING" },
  { nama: "Muhammad Aidul Shafiekri", password: "VOTING" },
  { nama: "Muhammad Salman Al Farisy", password: "VOTING" },
  { nama: "Nacita Cahyani", password: "VOTING" },
  { nama: "Novianeta", password: "VOTING" },
  { nama: "Nurhadinindya Prima", password: "VOTING" },
  { nama: "Putri Senja Kelana", password: "VOTING" },
  { nama: "Radiansyah", password: "VOTING" },
  { nama: "Rahya Satria Novizzan", password: "VOTING" },
  { nama: "Ratu Dhewi Hymeida", password: "VOTING" },
  { nama: "Rezky Aditya", password: "VOTING" },
  { nama: "Ruimasha An Nadirah", password: "VOTING" },
  { nama: "Salsabila Nazwa Hermansyah", password: "VOTING" },
  { nama: "Tiara Azkia Putri", password: "VOTING" },
  { nama: "Uray Muhammad Luthfi", password: "VOTING" },
  { nama: "Zahratussyifa", password: "VOTING" },
  { nama: "Zaskia", password: "VOTING" },
  { nama: "Zidan Alvino Effendi", password: "VOTING" },
  { nama: "Zievillia Al-Aqsa", password: "VOTING" },
  // Kelas X F
  { nama: "Al Muktadin Akbar Saputra", password: "VOTING" },
  { nama: "Almira Tungga Dewi", password: "VOTING" },
  { nama: "Alvin Widjaksono", password: "VOTING" },
  { nama: "Audrina Aura Zhalita", password: "VOTING" },
  { nama: "Azzaky Ibadurahman Dirgyantara", password: "VOTING" },
  { nama: "Cahya Vidi", password: "VOTING" },
  { nama: "Daris Farras Haidar", password: "VOTING" },
  { nama: "Elvina Zahra", password: "VOTING" },
  { nama: "Erdhio Dhaffi Alfarezi", password: "VOTING" },
  { nama: "Faris Zulfadly", password: "VOTING" },
  { nama: "Intan Permatasari", password: "VOTING" },
  { nama: "Iqbal Fikry Ahadin", password: "VOTING" },
  { nama: "Kaila Salsabilla", password: "VOTING" },
  { nama: "Khalifah Ar Rasyiid", password: "VOTING" },
  { nama: "Miftah Su'ud Su'ada", password: "VOTING" },
  { nama: "Muhamad Raka Pranata", password: "VOTING" },
  { nama: "Muhammad Aldian Nur Fathin", password: "VOTING" },
  { nama: "Muhammad Azmi Daffa", password: "VOTING" },
  { nama: "Muhammad Daffa Ziqullah", password: "VOTING" },
  { nama: "Mohamad Makayro Aprilano Albia", password: "VOTING" },
  { nama: "Muhammad Rangga Wichesyah", password: "VOTING" },
  { nama: "Muhammad Rava Maliki", password: "VOTING" },
  { nama: "Nailatul Ezzie", password: "VOTING" },
  { nama: "Nur Fitri Ramadhani", password: "VOTING" },
  { nama: "Pamorda Wardani", password: "VOTING" },
  { nama: "Putri Aisyah", password: "VOTING" },
  { nama: "Putri Arimbi", password: "VOTING" },
  { nama: "Rafid Zahid Rizqullah", password: "VOTING" },
  { nama: "Reisyarah Putri Arini", password: "VOTING" },
  { nama: "Reyhan Agustian Ramadhan", password: "VOTING" },
  { nama: "Richa Nabila", password: "VOTING" },
  { nama: "Rizki Afandi", password: "VOTING" },
  { nama: "Salwa Anjani", password: "VOTING" },
  { nama: "Syarifah Ierda Andini", password: "VOTING" },
  { nama: "Tasnita Lestari", password: "VOTING" },
  { nama: "Zaidan Fauzi Harahap", password: "VOTING" },
]

// votingOptions TIDAK lagi di sini — sekarang disimpan di tabel Supabase
// `voting_options` dan dikelola langsung dari Admin Dashboard (tambah/edit/hapus).
// Lihat supabase-schema.sql untuk seed data awal.

// Akun admin SEKARANG pakai Supabase Auth beneran (Authentication → Users di
// Supabase Dashboard), bukan hardcoded di sini lagi. Lihat supabase-schema.sql BAGIAN 4.
